const tasks={
intent:{kicker:'WHAT DOES THE HUMAN MEAN?',title:'Ground the request.',description:'Use speech, measured gaze, human and robot views, and interaction history to infer a grounded task description, target objects, destinations, and a nominal execution plan.',metrics:'Metrics: Slot F1 · Location accuracy · Plan exact match · Entity–visibility F1',label:'STRUCTURED INTENT · ILLUSTRATIVE',examples:[['Request','“Please bring that object over for me.”'],['Resolve','Object · destination · interaction context'],['Plan','Navigate → retrieve → navigate → hand over']]},
planning:{kicker:'WHAT SHOULD HAPPEN NEXT?',title:'Track progress. Update the plan.',description:'Combine grounded intent with current robot observations, state, and execution history to keep the current subtask, advance to the next, or end the episode.',metrics:'Metrics: Decision accuracy · Macro-F1 · Next type · Core subgoal · Completion F1',label:'CLOSED-LOOP DECISIONS · ILLUSTRATIVE',examples:[['Continue','The current subtask is still in progress.'],['Switch','Current subtask complete → predict the next subgoal.'],['Done','The episode goal has been satisfied.']]},
navigation:{kicker:'WHERE SHOULD THE ROBOT GO?',title:'Move through the household.',description:'A vision-language navigation model turns a navigation subgoal and visual context into movement commands. MID-360 LiDAR is additionally used for collision avoidance.',metrics:'Metrics: Offline action accuracy · Macro-F1 · STOP recall · STOP F1',label:'NAVIGATION EXECUTION · ILLUSTRATIVE',examples:[['Subgoal','Move toward the task-relevant location.'],['Actions','Forward · Left · Right · Stop'],['Evaluation','Compare predictions with recorded navigation targets.']]},
manipulation:{kicker:'HOW SHOULD THE ROBOT INTERACT?',title:'Turn a subgoal into motion.',description:'A VLA or world-action model uses robot observations, state, and a manipulation subgoal to generate low-level arm and gripper control commands.',metrics:'Metrics: Joint MSE · End-effector position error · End-effector rotation error',label:'MANIPULATION EXECUTION · ILLUSTRATIVE',examples:[['Input','Subgoal · robot camera views · robot state'],['Output','Arm and gripper action sequence'],['Evaluation','First predicted action and 24-step action chunks']]}
};
const resultSets={
intent:{title:'Human context resolves ambiguity.',caption:'Gemma-4-31B input ablations without interaction history. Scores are percentages.',headers:['Input condition','Slot F1 ↑','Location ↑','Plan EM ↑','RV F1 ↑','BERTScore ↑'],rows:[['Text only','60.38','19.42','33.24','N/A','92.96'],['Robot view','71.39','55.38','64.32','61.63','93.19'],['Human + robot','75.74','72.18','73.51','60.94','93.27'],['Human + robot + center prior','75.24','70.08','78.92','64.10','93.23'],['Human + robot + gaze','77.80','77.95','79.19','63.95','93.23']],chartLabel:'SLOT F1 (%) · HIGHER IS BETTER',chartCol:1,featured:[4],note:'Table 2. Measured gaze improves grounding beyond a center prior; the center-prior condition is slightly higher on entity–visibility F1.'},
history:{title:'Earlier interactions carry meaning.',caption:'Gemma-4-31B with full human and robot context plus gaze. Scores are percentages.',headers:['History condition','Slot F1 ↑','Location ↑','Plan EM ↑','RV F1 ↑','BERTScore ↑'],rows:[['No history','77.80','77.95','79.19','63.95','93.23'],['Predicted history','78.62','80.05','81.62','63.67','93.32'],['Ground-truth history (upper bound)','82.19','82.41','84.05','64.73','93.57']],chartLabel:'LOCATION ACCURACY (%) · HIGHER IS BETTER',chartCol:2,featured:[1],note:'Table 3. Predicted history improves grounding and nominal-plan accuracy. Ground-truth history is an oracle reference, not a deployable input.'},
planning:{title:'Intent improves subgoal quality.',caption:'All planners are fine-tuned on the HEIR training split. Scores are percentages.',headers:['Model / input','Accuracy ↑','Macro-F1 ↑','Next type ↑','Core ↑','Completion F1 ↑'],rows:[['Cosmos3-Nano · instruction','64.90','65.51','77.59','48.56','45.18'],['Cosmos3-Nano · + intent','65.62','66.19','82.18','64.37','52.24'],['Qwen3.5-4B · instruction','69.71','71.93','75.29','50.86','44.15'],['Qwen3.5-4B · + intent','69.23','71.40','73.56','59.48','46.84'],['Gemma-4-E4B-it · instruction','61.06','59.27','90.80','56.32','44.99'],['Gemma-4-E4B-it · + intent','62.02','60.14','93.10','65.80','50.24']],chartLabel:'CORE SUBGOAL CORRECTNESS (%) · HIGHER IS BETTER',chartCol:4,featured:[1,3,5],note:'Table 4. Core subgoal and completion scores improve for all three models; decision accuracy does not improve for every model. Next-subtask metrics are evaluated on ground-truth Switch cases.'},
navigation:{title:'Adaptation matters for navigation.',caption:'Offline VLN action prediction with English subgoals. Scores are percentages.',headers:['Model / weights','Accuracy ↑','Macro-F1 ↑','STOP recall ↑','STOP F1 ↑'],rows:[['NaVid · original','48.74','45.38','53.49','30.95'],['NaVid · fine-tuned','86.59','86.15','80.72','60.05'],['StreamVLN · original','46.84','39.65','19.39','20.34'],['StreamVLN · fine-tuned','86.36','86.20','75.49','67.02'],['InternVLA-N1 · original','49.08','45.41','58.28','31.48'],['InternVLA-N1 · fine-tuned','90.69','91.00','84.53','76.98']],chartLabel:'OFFLINE ACTION ACCURACY (%) · HIGHER IS BETTER',chartCol:1,featured:[1,3,5],note:'Table 5. Original means the released checkpoint without project LoRA. Fine-tuned checkpoints are selected on validation. STOP metrics are annotation-bounded proxies; offline accuracy is not real-robot navigation success.'},
manipulation:{title:'Compare actions, not just outcomes.',caption:'Fine-tuned VLA/WAM models with ground-truth subgoal instructions. Errors are lower-is-better.',headers:['Model','First MSE (rad²) ↓','First pos. (cm) ↓','First rot. (°) ↓','Chunk MSE (rad²) ↓','Chunk pos. (cm) ↓','Chunk rot. (°) ↓'],rows:[['DreamZero','0.002809','1.489','3.455','0.013215','2.604','5.244'],['π0-FAST','0.001644','0.808','1.093','0.009090','1.466','1.858'],['π0','0.000588','0.396','0.653','0.003688','0.937','1.499'],['π0.5','0.000468','0.373','0.652','0.003398','0.911','1.519'],['FastWAM','0.000374','0.369','0.673','0.002921','0.806','1.327'],['Lingbot-VLA2','0.000316','0.310','0.539','0.002633','0.725','1.194']],chartLabel:'24-STEP CHUNK POSITION ERROR (CM) · LOWER IS BETTER',chartCol:5,chartMax:3,featured:[5],note:'Table 6. Position and rotation columns are physical errors, not percentages. Evaluation uses ground-truth subgoals and recorded action targets; these scores do not measure end-to-end intent understanding.'}
};
function el(tag,text,className){const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(className)node.className=className;return node}
function setTask(key){const data=tasks[key];document.querySelectorAll('[data-task]').forEach(tab=>{const active=tab.dataset.task===key;tab.setAttribute('aria-selected',String(active));tab.tabIndex=active?0:-1});document.querySelector('#task-panel').setAttribute('aria-labelledby','task-tab-'+key);for(const field of ['kicker','title','description','metrics'])document.querySelector('#task-'+field).textContent=data[field];document.querySelector('#example-label').textContent=data.label;document.querySelector('#task-example-content').replaceChildren(...data.examples.map(([label,value])=>{const div=el('div');div.append(el('span',label),el('strong',value));return div}))}
const taskTabs=[...document.querySelectorAll('[data-task]')];taskTabs.forEach((tab,index)=>{tab.addEventListener('click',()=>setTask(tab.dataset.task));tab.addEventListener('keydown',event=>{let next;if(event.key==='ArrowRight')next=(index+1)%taskTabs.length;else if(event.key==='ArrowLeft')next=(index+taskTabs.length-1)%taskTabs.length;else if(event.key==='Home')next=0;else if(event.key==='End')next=taskTabs.length-1;else return;event.preventDefault();taskTabs[next].focus();setTask(taskTabs[next].dataset.task)})});
function renderResults(key){const data=resultSets[key];document.querySelector('#results-title').textContent=data.title;document.querySelector('#results-note').textContent=data.note;const table=document.querySelector('#results-table');const caption=el('caption',data.caption),head=el('thead'),headrow=el('tr'),body=el('tbody');data.headers.forEach(value=>{const th=el('th',value);th.scope='col';headrow.append(th)});head.append(headrow);data.rows.forEach((row,index)=>{const tr=el('tr',undefined,data.featured.includes(index)?'highlight-row':'');row.forEach((value,col)=>{const cell=el(col===0?'th':'td',value);if(col===0)cell.scope='row';tr.append(cell)});body.append(tr)});table.replaceChildren(caption,head,body);const chart=document.querySelector('#results-chart');chart.setAttribute('aria-label',data.chartLabel);chart.replaceChildren(el('div',data.chartLabel,'chart-label'),...data.rows.map((row,index)=>{const div=el('div',undefined,'chart-row'+(data.featured.includes(index)?' featured':''));const track=el('div',undefined,'bar-track'),bar=el('i');bar.style.width=Math.min(100,Number(row[data.chartCol])/(data.chartMax||100)*100)+'%';track.setAttribute('aria-hidden','true');track.append(bar);div.append(el('span',row[0]),track,el('strong',row[data.chartCol]));return div}))}
document.querySelector('#results-select').addEventListener('change',event=>renderResults(event.target.value));renderResults('intent');
const dialog=document.querySelector('#figure-dialog');document.querySelectorAll('.hero-scene>img,.wide-figure img').forEach(image=>{const button=el('button');button.type='button';button.className='figure-zoom';button.setAttribute('aria-label','Enlarge '+image.alt);image.parentNode.insertBefore(button,image);button.append(image);button.addEventListener('click',()=>{const expanded=document.querySelector('#enlarged-figure');expanded.src=image.src;expanded.alt=image.alt;dialog.showModal()})});document.querySelector('#close-figure').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',event=>{if(event.target===dialog){const box=dialog.getBoundingClientRect();if(event.clientX<box.left||event.clientX>box.right||event.clientY<box.top||event.clientY>box.bottom)dialog.close()}});
const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting)document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.hash==='#'+entry.target.id))})},{rootMargin:'-15% 0px -60% 0px'});document.querySelectorAll('section[id]').forEach(section=>observer.observe(section));
